name: "Git Operations"
description: "Handles git operations like commits, PRs, and branches"
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  files:
    description: 'Files to commit (space-separated)'
    required: true
  commit-message:
    description: 'Commit message'
    required: true
  create-pr:
    description: 'Whether to create a PR'
    required: false
    default: 'false'
  base:
    description: 'Base branch for PR'
    required: false
    default: 'staging'
  pr-title:
    description: 'PR title'
    required: false
  pr-body:
    description: 'PR description'
    required: false
  branch-name:
    description: 'Branch to create/use'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run Git Operations
      uses: ./actions/composite/git_ops
      with:
        github-token: ${{ inputs.github-token }}
        files: ${{ inputs.files }}
        commit-message: ${{ inputs.commit-message }}
        create-pr: ${{ inputs.create-pr }}
        base: ${{ inputs.base }}
        pr-title: ${{ inputs.pr-title }}
        pr-body: ${{ inputs.pr-body }}
        branch-name: ${{ inputs.branch-name }}