name: "Version Calculation"
description: "Calculates next version number based on git tags and configuration"
outputs:
  next_version:
    description: 'Calculated next version number'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run Version Calculator
      id: version
      uses: ./actions/core/version_calculator
      
    - name: Set outputs
      shell: bash
      run: echo "next_version=${{ steps.version.outputs.next_version }}" >> $GITHUB_OUTPUT