# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: "staging"
  # Unfortunately, Dependabot doesn't support custom prefixes like "develop/patch-"
  # It uses fixed patterns like "dependabot/github_actions/package-version"
  # However, we can use labels and assignees to help manage these PRs
  labels:
    - "dependencies"
    - "github-actions"
    - "develop"
  assignees:
    - "mattbuske"
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: "staging"
  labels:
    - "dependencies"
    - "python"
    - "develop"
  assignees:
    - "mattbuske"
#- package-ecosystem: gitsubmodule
#  directory: "/"
#  schedule:
#    interval: daily
#  open-pull-requests-limit: 10
#  target-branch: "staging"
#  pull-request-branch-name:
#    separator: "/"
