services:

  # This service runs the documentation for Secure Coding Standards for SUNY Upstate
  mkdocs-scs:
    # Vars are set in the .env file
    image: deepworks-net/github-toolkit-docs:${MKDOCS_IMAGE_VERSION:?err}
    build:
      context: .
    # Run MkDocs
    command: mkdocs serve -a 0.0.0.0:${MKDOCS_PORT:-8000}
    # Mount The Volumes
    volumes:
      - .:/docs
      - ./site:/docs/site
    # Ports
    ports:
      - "${MKDOCS_PORT:-8000}:${MKDOCS_EXTERNAL_PORT:-8000}"
    #hostname: mkdocs.upstate.local # Not Used Yet
    # Extra Environmental Variables
    environment:
      - ENVIRONMENT=development
      - WATCH_DOCS=true