services:

  # This service runs the documentation
  mkdocs-scs:
    # Vars are set in the .env file
    image: deepworks-net/github-toolkit-docs:${MKDOCS_IMAGE_VERSION:?err}
    build:
      context: .
    # Run MkDocs
    command: mkdocs serve -a 0.0.0.0:${MKDOCS_PORT:-8000}
    # Mount The Volumes
    volumes:
      - .:/docs
      - ./site:/docs/site
    # Ports
    ports:
      - "${MKDOCS_PORT:-8000}:${MKDOCS_EXTERNAL_PORT:-8000}"
    # Extra Environmental Variables
    environment:
      - ENVIRONMENT=development
      - WATCH_DOCS=true

  claude-code:
    image: deepworks/claude-code:latest
    volumes:
      # Main repository mount
      - .:/home/coder/project:rw
      # Source repo's config/models/validation folders
      - ./claude/config:/home/coder/claude/config:rw
      - ./claude/models:/home/coder/claude/models:ro
      - ./claude/validation:/home/coder/claude/validation:ro
      # Documentation
      - ./CLAUDE.md:/home/coder/CLAUDE.md:ro
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    working_dir: /home/coder/project
    tty: true
    stdin_open: true
    command: tail -f /dev/null