name: "Git Tag Operations"
description: "Handles Git tag operations like creation, deletion, and listing"
inputs:
  action:
    description: "The action to perform (create/delete/push/list)"
    required: true
  tag_name:
    description: "Name of the tag to operate on"
    required: false
  message:
    description: "Message for annotated tags"
    required: false
  remote:
    description: "Whether to operate on remote tags"
    required: false
    default: "false"
  pattern:
    description: "Pattern for listing tags"
    required: false
outputs:
  tags:
    description: "Comma-separated list of tags (when listing)"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    INPUT_ACTION: ${{ inputs.action }}
    INPUT_TAG_NAME: ${{ inputs.tag_name }}
    INPUT_MESSAGE: ${{ inputs.message }}
    INPUT_REMOTE: ${{ inputs.remote }}
    INPUT_PATTERN: ${{ inputs.pattern }}
branding:
  icon: "tag"
  color: "blue"