name: "Release Notes"
description: "Generates release notes from PRs and commits"
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  mode:
    description: 'Operation mode (prepare-release, unreleased)'
    required: true
  version:
    description: 'Version for the release'
    required: false
  pr-number:
    description: 'PR number to include in notes'
    required: false
  pr-title:
    description: 'PR title for notes'
    required: false

outputs:
  content:
    description: 'Generated release notes content'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run Release Notes
      id: notes
      uses: ./actions/composite/release_notes
      with:
        github-token: ${{ inputs.github-token }}
        mode: ${{ inputs.mode }}
        version: ${{ inputs.version }}
        pr-number: ${{ inputs.pr-number }}
        pr-title: ${{ inputs.pr-title }}

    - name: Set outputs
      shell: bash
      run: echo "content=${{ steps.notes.outputs.content }}" >> $GITHUB_OUTPUT