name: "Release Notes"
description: "Manages release notes content in draft releases"
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  mode:
    description: 'Operation mode (pr-merge, prepare-release)'
    required: true
  pr-number:
    description: 'PR number for pr-merge mode'
    required: false
  pr-title:
    description: 'PR title for pr-merge mode'
    required: false
  version:
    description: 'Version for prepare-release mode'
    required: false
outputs:
  content:
    description: 'Release notes content'
    
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
    INPUT_MODE: ${{ inputs.mode }}
    INPUT_PR_NUMBER: ${{ inputs.pr-number }}
    INPUT_PR_TITLE: ${{ inputs.pr-title }}
    INPUT_VERSION: ${{ inputs.version }}