name: "Version Update"
description: "Updates version numbers in specified files"
inputs:
  version:
    description: 'Version number to set'
    required: true
  files:
    description: 'Files to update (space-separated)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run Version Updater
      uses: ./actions/core/version_updater
      with:
        version: ${{ inputs.version }}
        files: ${{ inputs.files }}