name: "Git Branch Operations"
description: "Handles Git branch operations like creation, deletion, checkout, and listing"
inputs:
  action:
    description: "The action to perform (create/delete/checkout/list)"
    required: true
  branch_name:
    description: "Name of the branch to operate on"
    required: false
  start_point:
    description: "Starting point for branch creation"
    required: false
  force:
    description: "Whether to force delete branch"
    required: false
    default: "false"
  remote:
    description: "Whether to operate on remote branches"
    required: false
    default: "false"
  create:
    description: "Whether to create branch when checking out"
    required: false
    default: "false"
  all:
    description: "Whether to list all branches"
    required: false
    default: "false"
outputs:
  branches:
    description: "Comma-separated list of branches (when listing)"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    INPUT_ACTION: ${{ inputs.action }}
    INPUT_BRANCH_NAME: ${{ inputs.branch_name }}
    INPUT_START_POINT: ${{ inputs.start_point }}
    INPUT_FORCE: ${{ inputs.force }}
    INPUT_REMOTE: ${{ inputs.remote }}
    INPUT_CREATE: ${{ inputs.create }}
    INPUT_ALL: ${{ inputs.all }}
branding:
  icon: "git-branch"
  color: "blue"