# .github/workflows/core_action.version_calculator.yml
name: Core - Version Calculator

on:
  workflow_dispatch:  # allows manual triggering
  workflow_call:
    inputs:
      default_version:
        type: string
        required: false
        default: 'v0.1.0'
      version_prefix:
        type: string
        required: false
        default: 'v'
      tag_pattern:
        type: string
        required: false
        default: 'v*'
    outputs:
      next_version:
        description: "Calculated next version"
        value: ${{ jobs.calculate-version.outputs.next_version }}
      current_version:
        description: "Current version"
        value: ${{ jobs.calculate-version.outputs.current_version }}
      commit_count:
        description: "Commit count since last tag"
        value: ${{ jobs.calculate-version.outputs.commit_count }}

jobs:
  calculate-version:
    runs-on: ubuntu-latest

    outputs:
      next_version: ${{ steps.calculate-version.outputs.next_version }}
      current_version: ${{ steps.calculate-version.outputs.current_version }}
      commit_count: ${{ steps.calculate-version.outputs.commit_count }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}  # Ensures the current repository
          ref: main
          fetch-depth: 0
      
      - name: Calculate next version
        id: calculate-version
        uses: deepworks-net/github.toolkit/actions/core/version_calculator@v1
        with:
          default_version: ${{ inputs.default_version }}
          version_prefix: ${{ inputs.version_prefix }}
          tag_pattern: ${{ inputs.tag_pattern }}
