name: Prepare Release Branch

on:
  push:
    tags:
      - 'prep'  # Simple trigger
  workflow_call:
    inputs:
      base-branch:
        description: 'Base branch to create release from'
        required: false
        type: string
        default: 'staging'
      version-prefix:
        description: 'Prefix for version tags'
        required: false
        type: string
        default: 'v'
    secrets:
      github-token:
        description: 'GitHub token for API access'
        required: true

jobs:
  create-release-branch:
    if: (github.event_name == 'push' && github.ref_type == 'tag' && github.ref == 'refs/tags/prep') || github.event_name == 'workflow_call'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}  # Ensures the current repository
          ref: ${{ inputs.base-branch || 'staging' }}  # Use input or default to staging
          fetch-depth: 0
      
      # Ensure we have a clean environment with a proper branch
      - name: Setup Environment
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Make sure we have a proper branch to work with
          git fetch origin
          
          # Get the target branch
          target_branch="${{ inputs.base-branch || 'staging' }}"
          
          # Check if we're in detached HEAD state and fix if needed
          if git symbolic-ref -q HEAD > /dev/null; then
            echo "Already on a branch"
          else
            echo "In detached HEAD state, creating a working branch"
            # Create a working branch from our current state
            git checkout -b working-branch
            # Fetch and check out the target branch
            git fetch origin ${target_branch}:${target_branch} || true
            git checkout ${target_branch}
          fi
          
      - name: Calculate Version
        uses: ./actions/core/version_calculator
        id: version
        with:
          version_prefix: ${{ inputs.version-prefix || 'v' }}

      - name: Update Version Numbers
        uses: ./actions/core/version_updater
        with:
          version: ${{ steps.version.outputs.next_version }}
          files: 'mkdocs.yml'

      - name: Get Release Content
        uses: ./actions/composite/release_notes
        id: notes
        with:
          github-token: ${{ secrets.github-token || secrets.GITHUB_TOKEN }}
          mode: 'prepare-release'
          version: ${{ steps.version.outputs.next_version }}

      - name: Update Changelog File
        uses: ./actions/composite/update_changelog
        with:
          content: ${{ steps.notes.outputs.content }}
          mode: 'release'
          version: ${{ steps.version.outputs.next_version }}

      - name: Create Release Branch & PR
        uses: ./actions/composite/git_ops
        with:
          github-token: ${{ secrets.github-token || secrets.GITHUB_TOKEN }}
          files: 'CHANGELOG.md'
          commit-message: 'Prepare release ${{ steps.version.outputs.next_version }}'
          create-pr: true
          pr-title: 'Release ${{ steps.version.outputs.next_version }}'