name: MkDocs gh-pages Publish

on:
  # Keep existing trigger for this repo
  push:
    branches: 
      - main
  # Add workflow_call to make it reusable
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        default: '3.x'
        required: false
        type: string
      requirements-file:
        description: 'Path to requirements.txt'
        default: 'requirements.txt'
        required: false
        type: string
      readme-source:
        description: 'Source path for README.md'
        default: 'README.md'
        required: false
        type: string
      readme-destination:
        description: 'Destination path for README.md'
        default: 'docs/repo/inc/README.md'
        required: false
        type: string
      changelog-source:
        description: 'Source path for CHANGELOG.md'
        default: 'CHANGELOG.md'
        required: false
        type: string
      changelog-destination:
        description: 'Destination path for CHANGELOG.md'
        default: 'docs/repo/inc/CHANGELOG.md'
        required: false
        type: string
      license-source:
        description: 'Source path for LICENSE.md'
        default: 'LICENSE.md'
        required: false
        type: string
      license-destination:
        description: 'Destination path for LICENSE.md'
        default: 'docs/repo/inc/LICENSE.md'
        required: false
        type: string
    secrets:
      github-token:
        description: 'GitHub token for API access'
        required: true

jobs:
  deploy_gh_pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          token: ${{ secrets.github-token || secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version || '3.x' }}
      - name: Install dependencies
        run: |
          pip install -r ${{ inputs.requirements-file || 'requirements.txt' }}
          pip install ruamel.yaml
      - run: mkdocs gh-deploy --force
