name: Update Changelog

on:
  pull_request:
    branches:
      - staging
    types: [closed]
  workflow_call:
    inputs:
      pr-number:
        description: 'Pull request number for changelog updates'
        required: false
        type: string
      pr-title:
        description: 'Pull request title for changelog updates'
        required: false
        type: string
    secrets:
      github-token:
        description: 'GitHub token for release creation'
        required: true

permissions:
  contents: write  # for modifying changelog
  pull-requests: read  # for PR info

jobs:
  update_changelog:
    # Only run if the PR was merged (not just closed)
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}  # Ensures the current repository
          ref: staging    # Updated to new naming convention
          fetch-depth: 0

      - name: Calculate Next Version
        uses: ./actions/core/version_calculator
        id: version

      - name: Get Release Content
        uses: ./actions/composite/release_notes
        id: notes
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          mode: 'prepare-release'
          pr-number: ${{ github.event.pull_request.number }}
          pr-title: ${{ github.event.pull_request.title }}
          
      - name: Update Changelog File
        uses: ./actions/composite/update_changelog
        with:
          content: ${{ steps.notes.outputs.content }}
          mode: 'unreleased'
          version: ${{ steps.version.outputs.next_version }}
      
      - name: Commit Changes
        uses: ./actions/composite/git_ops
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: 'CHANGELOG.md'
          commit-message: 'Update changelog for PR #${{ github.event.pull_request.number }}'
          create-pr: false